apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.kiosklocktask'
version = '0.0.1'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace 'expo.modules.kiosklocktask'
  defaultConfig {
    versionCode 1
    versionName '0.0.1'
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation project(':expo-modules-core')
}
